### ISSUE TITLE
Add-on removes itself when disabled

### ISSUE THREAD

**Issue by Osmose** [mozilla/addon-recommendation-shield-study#14]
If I disable the add-on from `about:addons`, the add-on shows the post-study survey and removes itself. Showing the survey makes sense to me, but I find it weird that an add-on I only meant to disable automatically removes itself. I'm not sure if that's the right thing to do, though.

@gregglind Thoughts?

**Comment by gregglind** [comment]
That is by design.  My claim is that we should agressively respond to user
intent  to end the study.

I could be convinced otherwise.  We have heard 0 user complaint before this.

**Comment by Osmose** [comment]
Nah, sounds fine to me. Thanks!
