### ISSUE TITLE
"Why do I see this?" panel overflows

### ISSUE THREAD

**Issue by Osmose** [mozilla/addon-recommendation-shield-study#16]
<img width="415" alt="screen shot 2016-07-29 at 11 43 55 am" src="https://cloud.githubusercontent.com/assets/193106/17260441/46294d9e-5585-11e6-8263-b48664fce33d.png">

On Firefox 47, when I click the "Why do I see this?" button, the overlay overflows and covers the panel, showing scroll bars.

Also, the contrast on the text inside that overlay is low, we could be using a darker grey in there.

**Comment by bentoncase** [comment]
The colors that I'm using are from the mockup. Is that alright for me to darken them?

**Comment by Osmose** [comment]
> The colors that I'm using are from the mockup. Is that alright for me to darken them?

Yes.
