### ISSUE TITLE
"Disable all recommendations" link should be on it's own line

### ISSUE THREAD

**Issue by Osmose** [mozilla/addon-recommendation-shield-study#17]
<img width="415" alt="screen shot 2016-07-29 at 11 43 55 am" src="https://cloud.githubusercontent.com/assets/193106/17260491/8d59de9a-5585-11e6-87c9-92b0aba53ae2.png">

(Screenshot also includes the overflow bug from #16)

The link to disable all recommendations should be on it's own line below the paragraph, rather than at the end of the paragraph.

**Comment by bentoncase** [comment]
<img width="421" alt="screen shot 2016-07-29 at 12 39 04 pm" src="https://cloud.githubusercontent.com/assets/12304716/17261108/07545dd0-5589-11e6-983e-8739dc4a149b.png">
How's this?

**Comment by Osmose** [comment]
Definitely better!

It could use consistent padding around the edges, and could use some more contrast. http://webaim.org/resources/contrastchecker/ is a good tool for finding what a readable contrast between two colors would be.

As a side note, are there any domains with more than one recommendation? I'd like to test out the behavior when the panel is larger.

**Comment by bentoncase** [comment]
The add-on has 4 recommendations on Facebook, the most out of any domain.
