### ISSUE TITLE
Uninstalling and reinstalling the add-on without restarting breaks the panel

### ISSUE THREAD

**Issue by Osmose** [mozilla/addon-recommendation-shield-study#18]
If I uninstall the add-on and then re-install it within Firefox without restarting Firefox itself, the panel stops showing up when I click the button to bring it up.

I doubt this will be a common occurrence among the release population when we test the study, but I suspect it will be common among Mozillians who help test it out.

@MattGrimes Do you think this is a blocker for the initial study?

**Comment by bentoncase** [comment]
I'm finding this quite difficult to fix. I've written a cleanup function that removes all of the buttons from their respective windows on uninstall, but the issue still persists. Additionally, it seems to only happen within the window that is used to uninstall the addon. Additional windows can handle the addon uninstalling and reinstalling just fine. @Osmose can we work on this together tomorrow?

**Comment by Osmose** [comment]
> @Osmose can we work on this together tomorrow?

Sure, I'll be in tomorrow.
