### ISSUE TITLE
include prefs files showing prefs usages.

### ISSUE THREAD

**Issue by gregglind** [mozilla/addon-recommendation-shield-study#2]
```
jpm xpi --prefs text-button-prefs.json
```

etc.

**Comment by bentoncase** [comment]
Where can I find documentation on using the --prefs flag?

**Comment by bentoncase** [comment]
@gregglind I don't know if this is necessary anymore, as there is now only one pref that affects UI. 'autoOpen' is pretty self-explanatory, and variations.js will demonstrate how it is used. Do you think I should still make this?

**Comment by gregglind** [comment]
I think it's a wontfix for now.  Future work can re-do this trivially.
