### ISSUE TITLE
THIS THING IS TOO AWESOME, but could use a little styling help.

### ISSUE THREAD

**Issue by gregglind** [mozilla/addon-recommendation-shield-study#3]
I cannot handle the awesome.

(also, styling could be improved)
<img width="784" alt="screen shot 2016-07-12 at 7 07 33 pm" src="https://cloud.githubusercontent.com/assets/163983/16786632/3c94bcc4-4864-11e6-9ef0-483ca0f744f9.png">

**Comment by bentoncase** [comment]
How's this for style? 

<img width="746" alt="screen shot 2016-07-12 at 5 54 32 pm" src="https://cloud.githubusercontent.com/assets/12304716/16788390/640eaa86-4859-11e6-9ff6-8e04e41fe507.png">

I think that adding a Firefox icon makes it look more official and trustworthy.

**Comment by raymak** [comment]
+1 for the new style
