### ISSUE TITLE
add a 'works with e10s' handling thingy.

### ISSUE THREAD

**Issue by gregglind** [mozilla/addon-recommendation-shield-study#4]
in particular, in FUTURE, addons won't actaully be restartless.
49+

talk to AMY TSAY or SHELL ESCALANTE about this.  

Not sure on how to handle this.

**Comment by bentoncase** [comment]
Correct me if I'm wrong, but I believe that Mythmon realized that since this study itself is an add-on, users won't be on e10s. So we won't need to worry about users needing to restart to get off e10s.
