### ISSUE TITLE
Choose Better Site for Initial Demonstration

### ISSUE THREAD

**Issue by bentoncase** [mozilla/addon-recommendation-shield-study#42]
Currently the add-on opens a new tab of weather.com, and then shows the user a recommendation for weather. I choose this site without too much thought, and now I think it should definitely be changed to a better site. 

Weather.com has lots of annoying banner ads. It also requests the browser location, which causes Firefox to open a second panel, right next to the rec panel, asking if it is ok to provide location data.

@Osmose what site do you think would be a good choice for the demo?

**Comment by Osmose** [comment]
Wikipedia or Reddit, I think. @mattgrimes may have an opinion as well.

**Comment by gregglind** [comment]
I don't like Reddit as the site, mostly because super gross culture and bad
front page.  RES is awesome though.

I wish the Wikipedia addons were better.

Is there anything for MDN or such?  Or maybe a European site to demo "ok to
cookies"?

Sorry this is a hard problem!

**Comment by bentoncase** [comment]
We currently don't have any recommended add-ons for Wikipedia. What about [Wikiwand](https://addons.mozilla.org/en-US/firefox/addon/wikiwand-wikipedia-modernized/?src=search) as a recommended add-on? It looks pretty good to me: lots of users, lots of good reviews, no crap ads on install, and Wikipedia is a relatively neutral site.

**Comment by MattGrimes** [comment]
How about asking the AMO folks how they feel about recommending wikiwand?

**Comment by bentoncase** [comment]
Ok. What's the best way to reach them? Is there an irc channel I should ask, or an email list?

**Comment by Osmose** [comment]
@casebenton Scott DeVaney is the person we worked with to generate the list on the mailing list, you should ask him.

**Comment by gregglind** [comment]
Is this closed?

**Comment by bentoncase** [comment]
Not yet. Will be fixed when #59 merges
