### ISSUE TITLE
Please add a LICENSE file to this public repository.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/addon-recommendation-shield-study#5]
Whatever license you think is appropriate is fine, with the usual preference towards MPL2 when it's code.

**Comment by Osmose** [comment]
For reference, https://www.mozilla.org/en-US/MPL/ explains how to use the MPL (in short, add a LICENSE file with a copy of the MPL, mention the license at the bottom of the README, and put the license header at the top of all the code files.

One thing complicating this is that this repo includes files taken from https://github.com/gregglind/shield-studies-addon-utils/, which has no license. I filed https://github.com/gregglind/shield-studies-addon-utils/issues/15 to see about fixing that. In the long term we shouldn't be copy-pasting that code anyway, but pulling it in via npm.
