### ISSUE TITLE
TelemetryLog shouldn't be a singleton

### ISSUE THREAD

**Issue by Osmose** [mozilla/addon-recommendation-shield-study#58]
The `TelemetryLog` module defines a class for tracking telemetry data, and then instantiates one instance of the class an exports it. If there's only ever going to be one log ever, it shouldn't be defined as a class, but instead the methods should be defined as exports of the module, and the module itself should have private members tracking the state.

Alternatively, the class should be exported and instantiated where it is used, probably by the `Recommender` class.

There may even be a bug here: I can't see where these metrics are populated, which means they're reset every single time the code is reloaded, such as when Firefox starts up or when the add-on is reloaded. That needs to be tested though. Don't we want these stats that are being logged to be persistent?

**Comment by Osmose** [comment]
I can confirm that on DeveloperEdition, the view counts for the panel popup are reset upon browser reset and do not persist. That sounds like it will screw up the analysis.

@gregglind Is this a blocker?

**Comment by Osmose** [comment]
FWIW I measured panel view counts by inspecting the outgoing telemetry packet via `about:telemetry`.

**Comment by gregglind** [comment]
It is not for me.  They are all timestamped.  It's a nice to fix, and it
means the sequential doesn't increase across session

**Comment by gregglind** [comment]
As an alternative, put a 'session id' in the telemetry.  I can also sort that out very easily.  It is not needed, though, and not a blocker.
