### ISSUE TITLE
Generate signed XPI for internal testing

### ISSUE THREAD

**Issue by Osmose** [mozilla/addon-recommendation-shield-study#69]
Before putting in for review, we want to do a short round of internal testing to iron out any bugs. To do this, we need an XPI that:
1. Has a different ID than what we'll use for the actual study release, such that telemetry logs and the like can be distinguished from the real study.
2. Has the observe-only branch of the study disabled, so that everyone sees it functioning.
3. Is signed via the AMO auto-signing process.

**Comment by bentoncase** [comment]
Demo has been sent out! If I hear from anyone about bugs, I'll file them as issues.
