### ISSUE TITLE
User data is not persistent across browser restarts

### ISSUE THREAD

**Issue by bentoncase** [mozilla/addon-recommendation-shield-study#7]
Will use sdk's simple storage to keep user data

**Comment by raymak** [comment]
I claim that simple-storage is fairly but not fully reliable. It has an interval for syncing the data with the disk and if you crash Firefox during that interval, you lose data. I haven't actually tested this yet, but you could.

**Comment by bentoncase** [comment]
Is there a better way to store data across multiple sessions?

**Comment by raymak** [comment]
I've found [indexeddb](https://github.com/mozilla/normandy-addon/blob/master/lib/Storage.js) to be pretty good. And I wrote my (untested) [own module](https://github.com/raymak/contextualfeaturerecommender/blob/master/phase2/addon/lib/storage.js) to maintain an in-memory copy of the storage object (in hope of better performance) and a (untested) [module](https://github.com/raymak/contextualfeaturerecommender/blob/master/phase2/addon/lib/async-storage-wrapper.js) to scope the database. By _untested_ I mean there is no test code for it.

I think simple-storage would be good enough for your study though. Just know its limits.

**Comment by bentoncase** [comment]
Ok. I'm using storage to keep track of which recommendations have been seen in case of a restart. It wouldn't be terrible if simple-storage failed. Users may just see some popups after they already marked that they don't want to see them again.
