### ISSUE TITLE
DERIVE a simpler csv-ish version of the recommendations list for use by legal / privacy

### ISSUE THREAD

**Issue by gregglind** [mozilla/addon-recommendation-shield-study#70]
As part of the legal bug, please make a 'csv-ish' sort of list that has the existing sites and recommendations for easy linking.  A github'd file is fine.

**Comment by gregglind** [comment]
After looking at the actual recommendations list, maybe the json is actually enough here.  I will link to it from the privacy doc.

**Comment by gregglind** [comment]
Something like this is probably sufficient if we care:

```
$ node -e 'require("./data/recommendation/localData.json").forEach(function (x) {console.log(x.domain)})' > sites.txt

```

**Comment by gregglind** [comment]
Something like this is probably sufficient if we care:


```
  node -e 'require("./data/recommendation/localData.json").forEach(function (x) {console.log(x.domain)})' > sites.txt

```

**Comment by gregglind** [comment]
Something like this is probably sufficient if we care:


```js
  node -e 'require("./data/recommendation/localData.json").forEach(function (x) {console.log(x.domain)})' > sites.txt

```

**Comment by mythmon** [comment]
As an aside, a really good tool for doing this sort of json manipulation is [jq](https://stedolan.github.io/jq/). With it you could do the same as the node invocation like this:

``` shell
$ cat data/recommendation/localData.json | jq -r '.[].domain' > sites.txt
```
