### ISSUE TITLE
If the users has installed all the add-ons fade out the enhance button

### ISSUE THREAD

**Issue by MattGrimes** [mozilla/addon-recommendation-shield-study#83]
Especially in cases where there is only 1 add-on that applies, it is very likely that the user will have installed all the add-ons for a particular page. If that is the case, we should automatically hide the enhance button or grey it out. That way the user isn't constantly clicking on the icon thinking there are new things to discover. If we ended up adding a NEW add-on to a particular site, we could unhide the enhance button which would draw the user's attention once again. I feel like leaving the green icon on all the time will teach the user to ignore it.

**Comment by bentoncase** [comment]
This is a great point. Do you think it would be better to hide the icon or grey it out? I believe that they will both take about the same amount of time to implement.

**Comment by MattGrimes** [comment]
Maybe make it disappear completely? That way if it DOES come back because we've added new content it'll make it even more noticeable?

**Comment by raymak** [comment]
In the future we have to think about the UX of the icon and its color a bit more. Always green/showing is unnecessarily aggressive. Think about somebody who uses Facebook for hours everyday but is not interested in installing the addons.

**Comment by gregglind** [comment]
(currently, the site-enhance interface is also the obvious place to uninstall.  I am liking 'grey out' as per markus' design, IF we decide to do this.   Last time this came up, it was pushed off to future)
