### ISSUE TITLE
Auto-open panel should only open on first site visit, not every visit

### ISSUE THREAD

**Issue by bentoncase** [mozilla/addon-recommendation-shield-study#9]

**Comment by raymak** [comment]
I claim that this is unreasonably annoying to the user. If you are going with auto-open at all, make it a bit smarter at least imo. For instance, auto-open after 5 visits or 1 visit/ 10 min which might be a bit of a stretch.

**Comment by bentoncase** [comment]
So you mean that it would be good to have auto-open disable after 5 visits, or something like that? Can you please clarify what you think would be a good way to go about it? Thanks!

**Comment by Osmose** [comment]
For the record, this was an ask from mgrimes for the initial study release so we can compare auto-open vs no-auto-open. Fine-tuning the auto-open behavior seems like something we should focus on after the initial run to me.

**Comment by raymak** [comment]
Fair enough. I thought auto-open would be your only design. Thanks for clarifying. Benton, what I meant was that don't show auto open to the user unless they are regular users of the website (similar to Feature Recommender). But I think you are good for this study. Sorry for the confusion.

**Comment by bentoncase** [comment]
Oh I see now. That does sound like a good idea to try in the future. Thanks!
